import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SLajara Portfolio",
  description: "Generated by Samuel Lajara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#363636] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">{children}</body>
    </html>
  );
}
